'use client';

import React from 'react';
import Link from 'next/link';
import { ArrowLeft, FileText } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="bg-gray-50 min-h-screen">
      <div className="max-w-4xl mx-auto py-12 px-6 lg:py-24">
        <Link href="/" className="inline-flex items-center text-xs font-black  tracking-widest text-gray-400 hover:text-blue-600 transition-colors group mb-12">
           <ArrowLeft size={16} className="mr-2 group-hover:-translate-x-1 transition-transform" /> Back to Home
        </Link>
        
        <div className="bg-white rounded-[3rem] p-10 lg:p-20 shadow-xl border border-gray-100">
           <div className="flex items-center gap-4 mb-8">
              <div className="w-12 h-12 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center">
                 <FileText size={24} />
              </div>
              <h1 className="text-4xl font-black text-gray-900  tracking-tighter">Terms of Service</h1>
           </div>
           
           <div className="prose prose-blue max-w-none prose-headings:font-black prose-headings: prose-headings:tracking-tight prose-headings:text-gray-900 prose-p:font-medium prose-p:text-gray-500 prose-p:leading-relaxed">
              <p>Last updated: April 25, 2026</p>
              
              <h3>1. Acceptance of Terms</h3>
              <p>By accessing or using the VisionDrill platform, you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.</p>

              <h3>2. User Accounts</h3>
              <p>When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.</p>

              <h3>3. Intellectual Property</h3>
              <p>The Service and its original content, features and functionality are and will remain the exclusive property of VisionDrill and its licensors. Content generated by Instructors remains the intellectial property of the Instructor under a worldwide distribution license.</p>
           </div>
        </div>
      </div>
    </div>
  );
}
